name: daily-update-rivm-stats

on:
  push:
    branches:
      - main
  schedule:
    - cron: '10 13 * * *' # UTC time

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
          
      - name: install python packages
        run: pip install --upgrade --upgrade-strategy eager -r requirements.txt

      - name: calculate per-ggd per-age-group cases
        run: python calculate-ggd-pop-stats.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Daily update of data" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  