name: build-graphs

on:
  push:
    branches:
      - main

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements-nb.txt') }}
          
      - name: install python packages
        run: pip install --upgrade --upgrade-strategy eager -r requirements-nb.txt
        

      - name: execute notebook
        run: jupyter nbconvert --to html --execute age-group-plots.ipynb

      
      - name: prepare site
        run: |
          mkdir -p ./public
          cp *.html public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true